import type { StorefrontCategory, StorefrontProduct } from "./products";

export const FALLBACK_CATEGORIES: StorefrontCategory[] = [
  { name: "Fish", slug: "fish" },
  { name: "Shellfish", slug: "shellfish" },
  { name: "Crab", slug: "crab" },
  { name: "Squid", slug: "squid" },
  { name: "Prepared", slug: "prepared" },
];

export const FALLBACK_PRODUCTS: StorefrontProduct[] = [
  // Fish
  {
    id: "fb-fish-bangus-w1",
    productId: "fb-prod-bangus",
    variantId: "fb-fish-bangus-w1",
    name: "Bangus (Milkfish) — Whole 1kg",
    category: "Fish",
    categorySlug: "fish",
    price: 180,
    unit: "/kg",
    stock: 42,
    status: "In Stock",
  },
  {
    id: "fb-fish-bangus-bl500",
    productId: "fb-prod-bangus",
    variantId: "fb-fish-bangus-bl500",
    name: "Bangus (Milkfish) — Boneless 500g",
    category: "Fish",
    categorySlug: "fish",
    price: 130,
    unit: "/500g",
    stock: 30,
    status: "In Stock",
  },
  {
    id: "fb-fish-tilapia-w1",
    productId: "fb-prod-tilapia",
    variantId: "fb-fish-tilapia-w1",
    name: "Tilapia",
    category: "Fish",
    categorySlug: "fish",
    price: 150,
    unit: "/kg",
    stock: 60,
    status: "In Stock",
  },
  {
    id: "fb-fish-gg-1",
    productId: "fb-prod-gg",
    variantId: "fb-fish-gg-1",
    name: "Galunggong (Round Scad)",
    category: "Fish",
    categorySlug: "fish",
    price: 200,
    unit: "/kg",
    stock: 35,
    status: "In Stock",
  },
  {
    id: "fb-fish-tamban-1",
    productId: "fb-prod-tamban",
    variantId: "fb-fish-tamban-1",
    name: "Tamban (Sardines)",
    category: "Fish",
    categorySlug: "fish",
    price: 120,
    unit: "/kg",
    stock: 28,
    status: "In Stock",
  },
  {
    id: "fb-fish-tulingan-w1",
    productId: "fb-prod-tulingan",
    variantId: "fb-fish-tulingan-w1",
    name: "Tulingan (Mackerel Tuna)",
    category: "Fish",
    categorySlug: "fish",
    price: 220,
    unit: "/kg",
    stock: 18,
    status: "In Stock",
  },
  {
    id: "fb-fish-snapper-w1",
    productId: "fb-prod-snapper",
    variantId: "fb-fish-snapper-w1",
    name: "Maya-Maya (Red Snapper) — Whole 1kg",
    category: "Fish",
    categorySlug: "fish",
    price: 480,
    unit: "/kg",
    stock: 12,
    status: "In Stock",
  },
  {
    id: "fb-fish-snapper-f500",
    productId: "fb-prod-snapper",
    variantId: "fb-fish-snapper-f500",
    name: "Maya-Maya (Red Snapper) — Fillet 500g",
    category: "Fish",
    categorySlug: "fish",
    price: 320,
    unit: "/500g",
    stock: 8,
    status: "Low Stock",
  },
  {
    id: "fb-fish-grouper-w1",
    productId: "fb-prod-grouper",
    variantId: "fb-fish-grouper-w1",
    name: "Lapu-Lapu (Grouper)",
    category: "Fish",
    categorySlug: "fish",
    price: 550,
    unit: "/kg",
    stock: 9,
    status: "Low Stock",
  },
  {
    id: "fb-fish-dilis-500",
    productId: "fb-prod-dilis",
    variantId: "fb-fish-dilis-500",
    name: "Dilis (Anchovies)",
    category: "Fish",
    categorySlug: "fish",
    price: 140,
    unit: "/500g",
    stock: 24,
    status: "In Stock",
  },
  {
    id: "fb-fish-salmon-b500",
    productId: "fb-prod-salmon",
    variantId: "fb-fish-salmon-b500",
    name: "Salmon Belly",
    category: "Fish",
    categorySlug: "fish",
    price: 380,
    unit: "/500g",
    stock: 15,
    status: "In Stock",
  },
  {
    id: "fb-fish-tanigue-s1",
    productId: "fb-prod-tanigue",
    variantId: "fb-fish-tanigue-s1",
    name: "Tanigue (Spanish Mackerel)",
    category: "Fish",
    categorySlug: "fish",
    price: 600,
    unit: "/kg",
    stock: 7,
    status: "Low Stock",
  },

  // Shellfish
  {
    id: "fb-shell-hipon-1",
    productId: "fb-prod-hipon",
    variantId: "fb-shell-hipon-1",
    name: "Hipon (Suahe Shrimp) — 1kg",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 350,
    unit: "/kg",
    stock: 18,
    status: "In Stock",
  },
  {
    id: "fb-shell-hipon-500",
    productId: "fb-prod-hipon",
    variantId: "fb-shell-hipon-500",
    name: "Hipon (Suahe Shrimp) — 500g",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 185,
    unit: "/500g",
    stock: 20,
    status: "In Stock",
  },
  {
    id: "fb-shell-tahong-500",
    productId: "fb-prod-tahong",
    variantId: "fb-shell-tahong-500",
    name: "Tahong (Mussels) — 500g",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 120,
    unit: "/500g",
    stock: 4,
    status: "Low Stock",
  },
  {
    id: "fb-shell-tahong-1",
    productId: "fb-prod-tahong",
    variantId: "fb-shell-tahong-1",
    name: "Tahong (Mussels) — 1kg",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 220,
    unit: "/kg",
    stock: 6,
    status: "Low Stock",
  },
  {
    id: "fb-shell-talaba-doz",
    productId: "fb-prod-talaba",
    variantId: "fb-shell-talaba-doz",
    name: "Talaba (Oysters)",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 200,
    unit: "/doz",
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: "fb-shell-halaan-1",
    productId: "fb-prod-halaan",
    variantId: "fb-shell-halaan-1",
    name: "Halaan (Clams)",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 160,
    unit: "/kg",
    stock: 22,
    status: "In Stock",
  },
  {
    id: "fb-shell-scallop-500",
    productId: "fb-prod-scallop",
    variantId: "fb-shell-scallop-500",
    name: "Scallops",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 300,
    unit: "/500g",
    stock: 10,
    status: "Low Stock",
  },
  {
    id: "fb-shell-sugpo-1",
    productId: "fb-prod-sugpo",
    variantId: "fb-shell-sugpo-1",
    name: "Sugpo (Tiger Prawn) — 1kg",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 750,
    unit: "/kg",
    stock: 8,
    status: "Low Stock",
  },
  {
    id: "fb-shell-sugpo-500",
    productId: "fb-prod-sugpo",
    variantId: "fb-shell-sugpo-500",
    name: "Sugpo (Tiger Prawn) — 500g",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 390,
    unit: "/500g",
    stock: 9,
    status: "Low Stock",
  },
  {
    id: "fb-shell-curacha-1",
    productId: "fb-prod-curacha",
    variantId: "fb-shell-curacha-1",
    name: "Curacha (Spanner Crab)",
    category: "Shellfish",
    categorySlug: "shellfish",
    price: 520,
    unit: "/kg",
    stock: 5,
    status: "Low Stock",
  },

  // Crab
  {
    id: "fb-crab-alimasag-1",
    productId: "fb-prod-alimasag",
    variantId: "fb-crab-alimasag-1",
    name: "Alimasag (Blue Crab)",
    category: "Crab",
    categorySlug: "crab",
    price: 420,
    unit: "/kg",
    stock: 9,
    status: "Low Stock",
  },
  {
    id: "fb-crab-alimango-1",
    productId: "fb-prod-alimango",
    variantId: "fb-crab-alimango-1",
    name: "Alimango (Mud Crab) — 1kg",
    category: "Crab",
    categorySlug: "crab",
    price: 650,
    unit: "/kg",
    stock: 12,
    status: "In Stock",
  },
  {
    id: "fb-crab-alimango-j15",
    productId: "fb-prod-alimango",
    variantId: "fb-crab-alimango-j15",
    name: "Alimango (Mud Crab) — Jumbo 1.5kg",
    category: "Crab",
    categorySlug: "crab",
    price: 980,
    unit: "/1.5kg",
    stock: 4,
    status: "Low Stock",
  },
  {
    id: "fb-crab-talangka-500",
    productId: "fb-prod-talangka",
    variantId: "fb-crab-talangka-500",
    name: "Talangka (River Crab)",
    category: "Crab",
    categorySlug: "crab",
    price: 260,
    unit: "/500g",
    stock: 14,
    status: "In Stock",
  },

  // Squid
  {
    id: "fb-squid-pusit-1",
    productId: "fb-prod-pusit",
    variantId: "fb-squid-pusit-1",
    name: "Pusit (Squid) — 1kg",
    category: "Squid",
    categorySlug: "squid",
    price: 280,
    unit: "/kg",
    stock: 25,
    status: "In Stock",
  },
  {
    id: "fb-squid-pusit-500",
    productId: "fb-prod-pusit",
    variantId: "fb-squid-pusit-500",
    name: "Pusit (Squid) — 500g",
    category: "Squid",
    categorySlug: "squid",
    price: 150,
    unit: "/500g",
    stock: 18,
    status: "In Stock",
  },
  {
    id: "fb-squid-bisaya-500",
    productId: "fb-prod-bisaya",
    variantId: "fb-squid-bisaya-500",
    name: "Pusit Bisaya (Baby Squid)",
    category: "Squid",
    categorySlug: "squid",
    price: 190,
    unit: "/500g",
    stock: 11,
    status: "In Stock",
  },
  {
    id: "fb-squid-pugita-1",
    productId: "fb-prod-pugita",
    variantId: "fb-squid-pugita-1",
    name: "Octopus (Pugita)",
    category: "Squid",
    categorySlug: "squid",
    price: 420,
    unit: "/kg",
    stock: 6,
    status: "Low Stock",
  },

  // Prepared
  {
    id: "fb-prep-daing-2",
    productId: "fb-prod-daing",
    variantId: "fb-prep-daing-2",
    name: "Daing na Bangus (Marinated)",
    category: "Prepared",
    categorySlug: "prepared",
    price: 210,
    unit: "/pack",
    stock: 20,
    status: "In Stock",
  },
  {
    id: "fb-prep-tinapa-5",
    productId: "fb-prod-tinapa",
    variantId: "fb-prep-tinapa-5",
    name: "Tinapa (Smoked Fish)",
    category: "Prepared",
    categorySlug: "prepared",
    price: 180,
    unit: "/pack",
    stock: 16,
    status: "In Stock",
  },
  {
    id: "fb-prep-sisig-500",
    productId: "fb-prod-sisig",
    variantId: "fb-prep-sisig-500",
    name: "Bangus Sisig",
    category: "Prepared",
    categorySlug: "prepared",
    price: 250,
    unit: "/500g",
    stock: 12,
    status: "In Stock",
  },
  {
    id: "fb-prep-tocino-500",
    productId: "fb-prod-tocino",
    variantId: "fb-prep-tocino-500",
    name: "Fish Tocino",
    category: "Prepared",
    categorySlug: "prepared",
    price: 190,
    unit: "/500g",
    stock: 14,
    status: "In Stock",
  },
];
